<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2023-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Visualization Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be focusing on the visualization of data.

The data set will be presented to you in the form of a RDBMS.

You will have to use SQL queries to extract the data.

## Objectives

In this lab you will perform the following:

-   Visualize the distribution of data.

-   Visualize the relationship between two features.

-   Visualize composition of data.

-   Visualize comparison of data.

<hr>

## Demo: How to work with database

Download database file.

In [ ]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m4_survey_data.sqlite

Connect to the database.

In [ ]:
import sqlite3
conn = sqlite3.connect("m4_survey_data.sqlite") # open a database connection

Import pandas module.

In [ ]:
import pandas as pd

## Demo: How to run an sql query

In [ ]:
# print how many rows are there in the table named 'master'
QUERY = """
SELECT COUNT(*)
FROM master
"""

# the read_sql_query runs the sql query and returns the data as a dataframe
df = pd.read_sql_query(QUERY,conn)
df.head()

## Demo: How to list all tables

In [ ]:
# print all the tables names in the database
QUERY = """
SELECT name as Table_Name FROM
sqlite_master WHERE
type = 'table'
"""
# the read_sql_query runs the sql query and returns the data as a dataframe
pd.read_sql_query(QUERY,conn)

## Demo: How to run a group by query

In [ ]:
QUERY = """
SELECT Age,COUNT(*) as count
FROM master
group by age
order by age
"""
pd.read_sql_query(QUERY,conn)

## Demo: How to describe a table

In [ ]:
table_name = 'master'  # the table you wish to describe

QUERY = """
SELECT sql FROM sqlite_master
WHERE name= '{}'
""".format(table_name)

df = pd.read_sql_query(QUERY,conn)
print(df.iat[0,0])

# Hands-on Lab

## Visualizing distribution of data

### Histograms

Plot a histogram of `ConvertedComp.`

In [ ]:
# your code goes here
import seaborn as sns
import matplotlib.pyplot as plt
QUERY = " " "
SELECT ConvertedComp
FROM master

" " "
df = pd.read_sql_query(QUERY,conn)

sns.displot(df, height=7, aspect=1.5)

### Box Plots

Plot a box plot of `Age.`

In [ ]:
# your code goes here
QUERY = " " "
SELECT Age
FROM master

" " "
df = pd.read_sql_query(QUERY,conn)

print(df)
plt.reParams['figure.fiigsize'] = [15,8]
ax = sns.boxplot(data = df, orient = 'h')
ax.set_title('Age Distribution', size = 18)

plt.show()

## Visualizing relationships in data

### Scatter Plots

Create a scatter plot of `Age` and `WorkWeekHrs.`

In [ ]:
# your code goes here
QUERY = " " "
SELECT Age, WorkWeekHrs
FROM master

" " "
df = pd.read_sql_query(QUERY,conn)

print(df)
plt.reParams['figure.fiigsize'] = [15,8]
sns.scatterplot(data = df, x = 'Age', y = 'WorkWeekHrs')

plt.show()

### Bubble Plots

Create a bubble plot of `WorkWeekHrs` and `CodeRevHrs`, use `Age` column as bubble size.

In [ ]:
# your code goes here
QUERY = " " "
SELECT Age, WorkWeekHrs, CodeRevHrs
FROM master

" " "
df = pd.read_sql_query(QUERY,conn)

print(df)
plt.reParams['figure.fiigsize'] = [15,15]
sns.scatterplot(data = df, y = 'WorkWeekHrs', x = 'CodeRevHrs', size = 'Age', alpha = 0.6, sizes = (1,1000))

plt.show()

## Visualizing composition of data

### Pie Charts

Create a pie chart of the top 5 databases that respondents wish to learn next year. Label the pie chart with database names. Display percentages of each database on the pie chart.

In [ ]:
# your code goes here
QUERY = " " "
SELECT *, COUNT(*) AS count
FROM DatabaseDesireNextYear
GROUP BY DatabaseDesirNextYear
ORDER BY count DESC
LIMIT 5

" " "
df = pd.read_sql_query(QUERY,conn)
print(df)

data=df['count']
labels = df['DatabaseDesirNextYear']
plt.reParams['figure.fiigsize'] = [8,8]

fig, ax =plt.subplots()
ax.pie(data, labels = labels, autopct='%1.1f%%', explode=(0.1,0,0,0,0), shadow=True)

plt.show()

### Stacked Charts

Create a stacked chart of median `WorkWeekHrs` and `CodeRevHrs` for the age group 30 to 35.

In [ ]:
# your code goes here
QUERY = " " "
SELECT WorkWeekHrs, CodeRevHrs, Age
FROM master
WHERE age BETWEEN 30 AND 35 

" " "
df = pd.read_sql_query(QUERY,conn)

work_week = df['WorkWeekHrs'].quantile(0.5)
code_rev = df['CodeRevHrs'].quantile(0.5)
plt.rcParams['figure.figsize'] = [8,8]
fig, ax=plt.subplots()

ax.bar('AGE 30-35', work_week, label='WorkWeekHrs')
ax.bar('AGE 30-35', code_rev, bottom=work_week, label='WorkWeekHrs')

plt.show()

## Visualizing comparison of data

### Line Chart

Plot the median `ConvertedComp` for all ages from 45 to 60.

In [ ]:
# your code goes here
QUERY = " " "
SELECT CovertedComp, Age
FROM master
WHERE age BETWEEN 45 AND 60 

" " "
df = pd.read_sql_query(QUERY,conn)

medians = df.groupby('Age')['Convertedmap'].median()
data = pd.DataFrame(list(zip(medians.index, medians.values)),columns=['Age', 'MedCovertedComp'])
plt.rcParams['figure.figsize'] = [8,8]
sns.lineplot(data=data, x='Age', y='MedConvertedComp')

plt.show()

### Bar Chart

Create a horizontal bar chart using column `MainBranch.`

In [ ]:
# your code goes here
QUERY = " " "
SELECT MainBranch, COUNT(*) AS Frequency
FROM master
GROUP BY MainBranch 

" " "
df = pd.read_sql_query(QUERY,conn)

plt.rcParams['figure.figsize'] = [14, 8]

sns.barplot(data = df, y='MainBranch', x='frequency', orient='h')

plt.show()

Close the database connection.

In [ ]:
conn.close()

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2023-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).